
["Dalek Mod: Additions Common Config"]
	#Disable cyber drones explosive laser. Default = false
	disable_cyberdrone_laser = false
	#Disable the spawning of Dalek Mod mobs. Default = false
	disable_spawns = false
	#Disable special weapons daleks explosive laser. Default = false
	disable_swd_laser = false
	#Disable all explosive lasers. Default = false
	disable_explosive_laser = false
	#Maximum distance for randomizer. Default = 10000
	randomizer_max = 10000
	#Disable player locating. Default = false
	disable_player_locating = false
	#Disable BOTI effect. This only applies if Immersive Portals is installed. Default = false
	disable_boti = false

