#Changes the cost of the Food Cube
FoodCubeCost = 10
#Changes the rarity of the Vector Calculation Error, 0-100
#Range: 0 ~ 100
VectorErrorRarity = 15
#Changes the capacity of the Alternating Time Winds, 0-100
#Range: 0 ~ 100
AlternatingWindRarity = 10
#Changes the rarity of the Time Storm, 0-100
#Range: 0 ~ 100
StormRarity = 2
#Changes if calling a TARDIS into another TARDIS is allowed
OlimCallInOther = true

